port:  4000
markdown: kramdown
name: TaskList
url: http://gaelle2030.github.io
title: TaskList
description: "Tracking tasks for project management."
encoding: utf-8
timezone: America/New_York
gems:
  - jekyll-redirect-from
future: true